apiVersion: apps/v1
kind: Deployment
metadata: 
  name: bike
spec:
  replicas: 3
  selector: 
    matchLabels:
      app: bike
  template: 
    metadata:
      labels:
        app: bike
    spec: 
      enableServiceLinks: false
      serviceAccount: bike-sa
      containers:
        - name: bike
          image: julianorib/bike:v1.X
          ports:
            - name: http-web
              containerPort: 8080 
          resources:
            requests:
              memory: 100Mi
              cpu: 0.2
            limits:
              memory: 200Mi
              cpu: 0.4
          envFrom:
            - secretRef:
                name: bike-secret
