apiVersion: v1
kind: Service
metadata:
  name: bike-service
  labels:
    app: bike
spec:
  selector:
    app: bike
  ports:
    - name: http-web
      port: 80
      targetPort: 8080
  type: LoadBalancer